### ISSUE TITLE
mod_gnutls does not support Let's Encrypt OSCP

### ISSUE THREAD

**Issue by Forza-tng** [airtower-luna/mod_gnutls#3]
### Describe the bug

mod_gnutls uses SHA256 for signing OSCP requests, which does not work with Let's Encrypt.

### Version
mod_gnutls-0.11
gnutls-3.7.1
apache-2.4.48

### Comments
We can read in the _**Baseline Requirements section 4.9.10: On-line revocation checking requirements**_[[1]](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.3.pdf) that:
_OCSP responders operated by the CA SHALL support the HTTP GET method, as described in RFC 6960 **and/or** RFC 5019_

From what I can find out, the **RFC 6960**[[2]](https://datatracker.ietf.org/doc/html/rfc6960) does not say which hash algorithms to support, while the older **RFC 5019**[[3]](https://datatracker.ietf.org/doc/html/rfc5019#section-2.1.1) in section 2.1.1 says:
_Clients MUST use SHA1 as the hashing algorithm for the CertID.issuerNameHash and the CertID.issuerKeyHash values._

There has been a long thread about the issue over at the Let's Encrypt community forum[[4]](https://community.letsencrypt.org/t/support-mod-gnutls-with-apache/155015/43) which also lead to a feature request for SHA256 support with Let's Encrypt[[5]](https://github.com/letsencrypt/boulder/issues/5523)

It might a good thing for mod_gnutls to support Let's Encrypt as it is a very popular CA these days.

**Apache Logs**
<details>
<summary>Apache Logs</summary>

```
[Thu Jul 08 10:18:18.184778 2021] [gnutls:error] [pid 3743:tid 140005030573632] Invalid HTTP response status from r3.o.lencr.org: HTTP/1.0 400 Bad Request
[Thu Jul 08 10:18:18.194329 2021] [gnutls:error] [pid 3743:tid 140005030573632] (104)Connection reset by peer: [client 192.168.0.123:45403] Caching a fresh OCSP response failed
[Thu Jul 08 10:18:36.620187 2021] [gnutls:error] [pid 3724:tid 140005022180928] Invalid HTTP response status from r3.o.lencr.org: HTTP/1.0 400 Bad Request
[Thu Jul 08 10:18:36.620289 2021] [gnutls:error] [pid 3724:tid 140005022180928] (104)Connection reset by peer: [client 162.158.134.73:10982] Caching a fresh OCSP response failed
...very many lines...
[Thu Jul 08 20:40:55.240304 2021] [gnutls:error] [pid 3743:tid 140004055578176] Invalid HTTP response status from r3.o.lencr.org: HTTP/1.0 400 Bad Request
[Thu Jul 08 20:40:55.240428 2021] [gnutls:error] [pid 3743:tid 140004055578176] (104)Connection reset by peer: [client 2a01:4f9:c010:739b::1:41676] Caching a fresh OCSP response failed
[Thu Jul 08 20:41:08.445713 2021] [gnutls:error] [pid 3743:tid 140005030573632] Invalid HTTP response status from r3.o.lencr.org: HTTP/1.0 400 Bad Request
[Thu Jul 08 20:41:08.445801 2021] [gnutls:error] [pid 3743:tid 140005030573632] (104)Connection reset by peer: [client 104.197.157.91:33832] Caching a fresh OCSP response failed
```
```
[Thu Jul 08 10:17:46.849336 2021] [gnutls:warn] [pid 3719:tid 140005416871808] Could not create OCSP stapling configuration for certificate 1 in chain (CN=R3,O=Let's Encrypt,C=US): No OCSP URI in the certificate nor a GnuTLSOCSPResponseFile setting, cannot configure OCSP stapling.
[Thu Jul 08 10:17:46.898264 2021] [gnutls:warn] [pid 3720:tid 140005416871808] Could not create OCSP stapling configuration for certificate 1 in chain (CN=R3,O=Let's Encrypt,C=US): No OCSP URI in the certificate nor a GnuTLSOCSPResponseFile setting, cannot configure OCSP stapling.
```
</details>

[1] https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.3.pdf
[2] https://datatracker.ietf.org/doc/html/rfc6960
[3] https://datatracker.ietf.org/doc/html/rfc5019#section-2.1.1
[4] https://community.letsencrypt.org/t/support-mod-gnutls-with-apache/155015/43
[5] https://github.com/letsencrypt/boulder/issues/5523

**Comment by aarongable** [comment]
As a note, although RFC 5019 is older, it is not obsoleted by RFC 6960: rather, 5019 profiles/standardizes the "lightweight" OCSP profile, which is a restricted subset of the overall OCSP protocol standardized in 6960. The majority of the OCSP client ecosystem has settled on using SHA1 for this purpose, as the issuerNameHash and issuerKeyHash portions of an OCSP request do not need to be cryptographically secure, just statistically unique.

**Comment by airtower-luna** [comment]
Thank you for the detailed report, in particular the reference to RFC 5019! Certificate stapling with Let's Encrypt is definitely something I want to support. :slightly_smiling_face: I agree that using SHA1 for issue name hash and issue key hash won't create security problems, so switching the fixed hash might be the simplest solution. Or do you see any need to make the hash configurable?

Please test the fix in #4 and let me know if it works!

I haven't worked with Pebble before, would it be practical to add an integration test to ensure compatibility?

**Comment by airtower-luna** [comment]
I just checked the Pebble docs, and they say it doesn't include and OCSP responder. Are the exact checks that the Let's Encrypt responder enforces documented somewhere?

**Comment by aarongable** [comment]
Apologies for the delay! That's correct that Pebble doesn't include an OCSP responder; this is because Pebble is a minimal implementation of an ACME server, and OCSP is outside the scope of ACME.

I don't believe the exact checks that the LE OCSP responder uses are documented anywhere, but you can see them here: https://github.com/letsencrypt/boulder/blob/6eee230d699a7cb6483f54e34bb1e30df48bf0a1/cmd/ocsp-responder/main.go#L79

Namely, the set of Issuer certificates and Serial prefixes that it allows are configurable, but it always enforces that `crypto.SHA1` be the `issuerKeyHashAlgorithm`.
